/*
-- Query: SELECT * FROM foxter_db.products
LIMIT 0, 1000

-- Date: 2022-06-28 16:47
*/
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (4,'Buzo Puma Power Colorblock Full-Zip',15999,0,6,'El Buzo Puma Power Colorblock Full-Zip infunde a cualquier atuendo un estilo cool y urbano. Confeccionado en algodón, es perfecto para tener a mano los días frescos, pues te acompaña hasta la noche. Su diseño a dos colores y con el logo característico de la marca en los brazos te da toda la onda que te gusta reflejar.',1,2);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (22,'Buzo Lotto Smart II',6999,0,1,'El Buzo Lotto Smart II está confeccionado en algodón para una mayor sensación de comodidad al vestirlo durante todo el día. Su estilo regular con mangas que se ajustan a tus muñecas te protegen de las bajas temperaturas mientras salís a la calle. Su diseño liso, sin estampados, lo vuelve un must en tu ropero a la hora de combinarlo.',1,2);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (23,'Calza Dribbling Ciclismo 21',6800,0,7,'La Calza Dribbling Ciclismo 21 tiene todo lo necesario para acompañarte en tus carreras y entrenamientos. Su tela permite que te muevas libremente y sin restricciones, evitando la fricción. Cuenta con una bandana de protección que alivia la sensibilidad en zonas clave para que disfrutes de todo el tiempo que pases arriba de tu bicicleta.',1,2);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (24,'Pantalón Lotto Smart',5999,0,3,'El Pantalón Lotto Smart es un aliado perfecto para todos tus días. Confeccionado en algodón y poliéster para una mayor suavidad y durabilidad, posee bolsillos a los costados y un diseño liso, fácil de combinar con cualquier prenda para que nunca te falte un básico en tu ropero.',2,2);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (25,'Calza Lotto Smart',3500,0,7,'Las Calzas Lotto Smart están confeccionadas en poliéster para una mayor resistencia y durabilidad, además del máximo confort diario. Su estilo regular y diseño liso te permite vestirlas durante todo el día, ya que son una prenda cómoda para entrecasa como también para tus rutinas de entrenamiento.',2,2);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (26,'Traje de baño Speed con Broche',7949,20,8,'La tecnología Anticloro de Speed se refleja en el Traje de Baño Speed con Broche, ideal para acompañarte en todos tus movimientos bajo el agua sin perder la tranquilidad que te brinda esta malla gracias a su ajuste de breteles cruzados en la espalda.',2,1);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (27,'Previous Next Remera Lotto',3999,20,1,'Que nunca te falten los básicos; lleva la Remera Lotto Hs22 y asegurate una prenda que podes combinar con todo tu ropero. El corte clásico y las mangas cortas ayudan a mantenerte fresca y el diseño liso es liviano, perfecto para ir al trabajo o a la facultad con un look sobrio.',2,1);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (28,'Campera Lotto Dinámico',12599,10,2,'La Campera Lotto Dinámico es perfecta para los días más fríos del año; moderna, versátil, cómoda y discreta. El cuello alto, el cierre y la capucha te protegen de las bajas temperaturas y cuenta con bolsillos para llevar lo necesario con vos en cada salida.',1,1);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (29,'Pantalón Givova Entrenamiento',9599,10,3,'El Pantalón Givova Newell\'s Old Boys Entrenamiento muestra tu pasión por el equipo rosarino, con un diseño estampado con el escudo, cintura elástica y bolsillos para llevar todo con vos a la cancha, y un corte achupinado con cierres en los tobillos para regular el calce y llevarlo como prefieras.',3,1);
INSERT INTO `` (`idProduct`,`name`,`price`,`discount`,`idCategory`,`description`,`idSexCategory`,`idSaleCategory`) VALUES (30,'Musculosa Lotto Logo',2999,26,4,'Para los días de más calor es imprescindible contar con una remera de entrenamiento que te ayude. La Musculosa Lotto Logo cuenta con un cuello redondo para aportar frescura y, además, al no tener mangas favorece la ventilación. Su diseño sencillo con el logo en el pecho te da un look óptimo para darlo todo en tu rutina.',1,1);
